### PR TITLE
swap the parameter to make id in the first argument

### PR DESCRIPTION
**Pull request by jchen293**
# Description

Fix a mistake that I accidentally left for Java thread-safe PR. This PR swap the parameter to make the `id` in the first argument.

# Testing

Current tests pass

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

### CODE REVIEW

**Review by Justintime50 — DISMISSED** [review]

**Comment by jchen293** [comment]
> Are we positive these are the only ones?

Yes, 99% sure. I found out these three were the ones I accidentally left when I was doing the code examples yesterday.

**Comment by jchen293** [comment]
Forced push to resolve the merge conflict, rebasing from master branch.

**Review by Justintime50 — APPROVED** [review]

**Comment by nwithan8** [comment]
One more: 
image

**Review by nwithan8 — CHANGES_REQUESTED** [review]
Double-check to make sure we didn't miss anything

**Comment by jchen293** [comment]
> One more: image

This function wasn't caught because it was not used in the code example, good catch!

**Review by nwithan8 — APPROVED** [review]

**Review by Justintime50 — APPROVED** [review]

**Pull request merged**
