### PR TITLE
support one call buy order by adding service attribute in Order class.

### PR DESCRIPTION
**Pull request by jchen293**
Support one call buy order for Java library by adding service attribute in Order class and #87 add service in Shipment class.

### CODE REVIEW

**Review by Justintime50 — APPROVED** [review]

**Review by Justintime50 — CHANGES_REQUESTED** [review]
Actually, this needs the `carrier_accounts` array field too to properly do a one-call buy. Please also add a unit test to ensure this works properly.

**Review by Justintime50 — APPROVED** [review]
This now looks correct, thank you! 

Were you able to end-to-end test this @jchen293

**Comment by jchen293** [comment]
> Yes

**Comment by jchen293** [comment]
> This now looks correct, thank you!
> 
> Were you able to end-to-end test this @jchen293

Yes

**Review by nwithan8 — APPROVED** [review]

**Pull request merged**
