### PR TITLE
Verification

### PR DESCRIPTION
**Pull request by jchen293**
# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

# Description

Add missing classes: `verification`, `verifications`, and `verificationDetails`
Add extra assertion for `createAndVerify` Address.
Correct the type of `Verifications` in Address class attribute, according to our [API Doc](https://www.easypost.com/docs/api#verification-object). 

# Testing

E2E tested locally

Screen Shot 2022-04-14 at 6 59 45 PM

### CODE REVIEW

**Review by Justintime50 — APPROVED** [review]

**Review by Justintime50 — CHANGES_REQUESTED** [review]
It appears we already have a bunch of this already, it's called `AddressVerification`, there's probably no need to change it here.

Also, CHANGELOG entries are supposed to be in present tense `Adds` instead of `Added`, etc. Please put them back or correct them to present tense. Most of the changes here may not be necessary however.

**Review by Justintime50 — APPROVED** [review]
Just to make sure I understand this, we are adding the missing bridge here from an `Address` object down to it's `Verification` object by adding the missing `Verifications` object?

So it is going from `Address -> Verification` which is incorrect to `Address -> Verifications -> Verification` which now makes it accessible?

**Comment by jchen293** [comment]
> 

That's correct, so the user can access `zip4` and `delivery` from `Verification`, according to the API doc.

Screen Shot 2022-04-15 at 5 24 57 PM

**Review by nwithan8 — APPROVED** [review]
LGTM, mirrors what we have in [Go](https://github.com/EasyPost/easypost-go/blob/master/address.go) (which is what I'm going to start considering our reference for type-strict languages)

**Pull request merged**
