### PR TITLE
Fix incorrect test value

### PR DESCRIPTION
**Pull request by nwithan8**
Fixes an incorrect expected value that will cause the test to fail. Must have gotten lost in a rebase.

### CODE REVIEW

**Comment by Justintime50** [comment]
I'm confused why this is necessary unless this fee changed in the last couple hours. We just merged a commit without this fix and the tests passed fine earlier today.

**Review by jontsai — APPROVED** [review]

**Comment by nwithan8** [comment]
> I'm confused why this is necessary unless this fee changed in the last couple hours. We just merged a commit without this fix and the tests passed fine earlier today.

¯\_(ツ)_/¯

All I know is, tests are failing with "4.83" on the master branch, and not failing with "4.53"
image

**Review by jchen293 — APPROVED** [review]
Code LGTM, we might want to confirm if the fee actually got increased before the merge.

**Comment by fiendish** [comment]
Screen Shot 2021-12-30 at 4 03 30 PM

**Review by fiendish — APPROVED** [review]
This is ok, but checking for specific values against a server response where values change over time is not ideal.

**Comment by nwithan8** [comment]
> This is ok, but checking for specific values against a server response where values change over time is clearly not ideal.

VCR is on our radar.

**Comment by fiendish** [comment]
I'm also not a fan of VCR because it allows the client and server to desynchronize when someone fails to update the recordings. I'd rather test against a real server but not specific values.

**Review by Justintime50 — APPROVED** [review]
I guess, still confused why this broke in-between two PRs an hour apart, but this is a trivial change we can adjust if needed.

**Comment by fiendish** [comment]
It will break any time service rates change.

**Pull request merged**
