### PR TITLE
fix: checkstyle install target

### PR DESCRIPTION
**Pull request by Justintime50**
# Description

Fixes the install target to install checkstyle too, ignores jar files and sorts gitignore file.

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

### CODE REVIEW

**Comment by nwithan8** [comment]
I feel like there was a reason I went with wget rather than curl, but I can't remember. If it work, it works.

**Review by nwithan8 — APPROVED** [review]

**Comment by Justintime50** [comment]
> I feel like there was a reason I went with wget rather than curl, but I can't remember. If it work, it works.

`wget` is good for container workflows because it's often installed by default for Alpine Linux distros; however, the opposite is true of normal users where macOS isn't guaranteed to have it whereas it does `curl`. My approach is use the tool that the majority of the people using/maintaining the project are using so it works for the most amount of people out of the box.

**Review by jchen293 — APPROVED** [review]
Thanks for fixing this, I had to manually install `wget` on my Mac

**Comment by nwithan8** [comment]
> > I feel like there was a reason I went with wget rather than curl, but I can't remember. If it work, it works.
> 
> `wget` is good for container workflows because it's often installed by default for Alpine Linux distros; however, the opposite is true of normal users where macOS isn't guaranteed to have it whereas it does `curl`. My approach is use the tool that the majority of the people using/maintaining the project are using so it works for the most amount of people out of the box.

Gotcha. Meanwhile, I'm pretty sure I was on my Windows machine when I did this, which comes with neither pre-installed, but I had previously added both to my PATH, so... 🤷🏻

**Pull request merged**
