### PR TITLE
fix: bump easyvcr to fix vulnerabilities

### PR DESCRIPTION
**Pull request by Justintime50**
# Description

Bumps EasyVCR since we patched some vulnerabilities

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

### CODE REVIEW

**Comment by Justintime50** [comment]
Maven doesn't get a new binary for ~1-2 days so we need to wait to pull this in.

**Comment by nwithan8** [comment]
Maven reporting 0.5.1 is available now.

**Comment by nwithan8** [comment]
Yikes. Testing locally with new VCR package.

**Comment by nwithan8** [comment]
Patch for EasyVCR: https://github.com/EasyPost/easyvcr-java/pull/27

**Review by nwithan8 — APPROVED** [review]

**Pull request merged**
